In [2]:
import pandas as pd
import numpy as np 
import requests

In [3]:
df= pd.read_csv(r"C:\Users\himan\Education1\Projects\NLP\data\IMDB Dataset.csv", )
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review']= df['review'].str.lower

In [8]:
df.head(10)

                                              review sentiment
0  <bound method StringMethods.lower of <pandas.c...  positive
1  <bound method StringMethods.lower of <pandas.c...  positive
2  <bound method StringMethods.lower of <pandas.c...  positive
3  <bound method StringMethods.lower of <pandas.c...  negative
4  <bound method StringMethods.lower of <pandas.c...  positive
5  <bound method StringMethods.lower of <pandas.c...  positive
6  <bound method StringMethods.lower of <pandas.c...  positive
7  <bound method StringMethods.lower of <pandas.c...  negative
8  <bound method StringMethods.lower of <pandas.c...  negative
9  <bound method StringMethods.lower of <pandas.c...  positive